### ISSUE TITLE
Morning session

### ISSUE THREAD

**Issue by lucianosarno** [Prabhakarzx/HTMLforms-LucianoAndPrabhakar#1]
Lock icon is appearing white instead of its true appearence.

**Comment by Rocio01** [comment]
don´t forget Readme file (screenshot);

**Comment by SunnySparks** [comment]
Great job on making it responsive and as accurate as possible

**Comment by Prabhakarzx** [comment]
### Thank you @Rocio01 and @SunnySparks,
All the issues has been fixed. Thanks for your feedback, it means a lot to us.
Thank You!
