### ISSUE TITLE
Adjusting the textPart of icons

### ISSUE THREAD

**Issue by lucianosarno** [Prabhakarzx/HTMLforms-LucianoAndPrabhakar#5]
https://github.com/Prabhakarzx/HTMLforms-LucianoAndPrabhakar/blob/acd330898fcc56e168cab08cd52f197ebd127f24/index.html#L30-L38

I've got the exact original icons from the source, but if we look carefully, we'll see that the texts "mint / quickbooks / turbotax" are misaligned, and I would like to know more about how to solve this :)
It is done with .svg, I did some google but it appeared very complicated :/ 

Source >> https://accounts.intuit.com/signup.html?offering_id=Intuit.ifs.mint&namespace_id=50000026&redirect_url=https%3A%2F%2Fmint.intuit.com%2Foverview.event%3Futm_medium%3Ddirect%26cta%3Dhero_sign_up_free_ProspectWeb%26ivid%3D0b720966-3ddf-4f4d-9fac-dbc840bac13a%26adobe_mc%3DMCMID%253D35514261000221439911321019328239003039%257CMCORGID%253D969430F0543F253D0A4C98C6%252540AdobeOrg%257CTS%253D1591638859%26ivid%3D0b720966-3ddf-4f4d-9fac-dbc840bac13a

My Index >> https://github.com/Prabhakarzx/HTMLforms-LucianoAndPrabhakar/blob/feature-branch/index.html

**Comment by Prabhakarzx** [comment]
It was a great experience working on this project. The issue has be resolved.
Thank You!
